version: '3.1'

services:
  backend:
    build: 
      context: .
    image: backend
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    networks:
    - iteasyopsnetwork

networks:
  iteasyopsnetwork:
    external: true
