version: '3.1'

services:
  backend:
    build: 
      context: .
    image: backend
    container_name: backend
    restart: always
    environment:
      - TZ=Asia/Seoul
      - ENVIRONMENT=prod
    networks:
    - iteasyopsnetwork

networks:
  iteasyopsnetwork:
    external: true
