version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - iteasyopsnetwork

  backend:
    build: 
      context: .
    image: backend
    container_name: backend
    restart: always
    # ports:
    #   - 8080:8080
    environment:
      - TZ=Asia/Seoul
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - mongo
    networks:
    - iteasyopsnetwork

networks:
  iteasyopsnetwork:
    external: true
