---
- name: 비밀번호 변경하기
  hosts: all
  become: true
  gather_facts: false
  vars:
    account: ""
    change_password: ""

  tasks:
    - name: 비밀번호 변경
      ansible.builtin.user:
        name: "{{ account }}"
        update_password: always
        password: "{{ change_password | password_hash('sha512') }}"
      notify: Changed Password

  handlers:
    - name: Changed Password
      ansible.builtin.debug:
        msg: "Account: {{ account }}, New Password (hashed): {{ change_password | password_hash('sha512') }}"
