---
- name: 앤서블 초기화
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set up .ansible.cfg
      ansible.builtin.blockinfile:
        path: ~/.ansible.cfg
        create: true
        block: |
          [defaults]
          host_key_checking=False
          nocows=true
          deprecation_warnings=False
          # stdout_callback=json

    - name: SSH 키 페어 생성 (이미 존재하는 경우 생략)
      ansible.builtin.command: ssh-keygen -t rsa -f ~/.ssh/control_node -N ""
      args:
        creates: ~/.ssh/control_node

    - name: Update apt
      ansible.builtin.shell: apt-get update -y

    - name: Install necessary packages
      ansible.builtin.apt:
        pkg:
        - gcc
        - python3
        - python3-pip
        - curl
        - net-tools
        - vim
        - git
        - openssh-server
        - sshpass

    - name: Install roles
      ansible.builtin.command: ansible-galaxy install --force --ignore-errors -r requirements.yml -p roles
